language: node_js
node_js: node
cache:
    directories:
        - node_modules
        - .nvm
install: npm install eslint@3.6.1 eslint-plugin-html@1.5.3 eslint-config-airbnb@12.0.0
script: eslint src examples
